name: Update Database (Prod)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    name: Migrate Database
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install Prisma
        run: bun install

      - name: Migrate Database
        run: bunx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
